spring.application.name=demo

server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5433/${DB_NAME:demo}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

users.api.base-url=${USERS_API_BASE_URL:http://18.228.48.67}
